from abc import ABC, abstractmethod
from typing import Dict

class BrokerAdapter(ABC):
    @abstractmethod
    def connect(self) -> bool: ...
    @abstractmethod
    def account(self) -> Dict: ...
    @abstractmethod
    def positions(self) -> Dict: ...
    @abstractmethod
    def place_order(self, intent): ...
    @abstractmethod
    def cancel_order(self, order_id: str) -> bool: ...
